### ISSUE TITLE
Make inputs compatible with TIF

### ISSUE THREAD

**Issue by kbenoit** [ropensci/cld2#2]
I'd suggest defining two input objects, the (optionally named) character vector as it is now, and a data.frame with a named `text` column. This conforms to the [Text Interchange Format](https://github.com/ropensci/tif) and is nearly costless to implement.

**Comment by jeroen** [comment]
Fixed in https://github.com/ropensci/cld2/commit/232bd0e6bc2a42f4465367118ab2a740b3517dec
